name: Github Actions 실행시켜보기

# 들여쓰기 중요 푸쉬가 될 떄마다 즉 메인 브랜치에 푸쉬 할 떄마다 이러한 작업을 해줘 메인이 아니라면 실행 시키지마
on:
  push:
    branches:
      - main


jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    # 한가지 일을 자동화
    steps:
      - name: Hello World 출력하기
        run: echo "Hello World"
      # 여려 명령어 실행하기 여려 일을 자동화 시키기
      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"
          pwd

      - name: Github Actions 자체 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA

      - name: Github Actions Secret 변수 사용해보기2
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_HOBBY }}